### ISSUE TITLE
Windows program files path and executable are incorrect

### ISSUE THREAD

**Issue by harelba** [iliapolo/pyci#67]
program files path cannot be determined (needed in order to control overriding the existing folder when updating from a non-pyci installation).

executable name is the original name (q-AMD64-Windows.exe instead of q.exe in this case).

**Comment by iliapolo** [comment]
These issues were already resolved and are in fact duplicates of #63 and #65.

The fixes are part of release [0.8.2](https://github.com/iliapolo/pyci/releases/tag/0.8.2)

Closing this issue.
